server:
  port: 9090

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: msvc-activity
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gym_activities_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eurekaost:8761/eureka

springdoc:
  api-docs:
    path: /api/v2/activities
  swagger-ui:
    path: /activity/swagger-ui.html