eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clients
          uri: http://localhost:8090
          predicates:
            - Path=/api/v2/clients/**

        - id: activities
          uri: http://localhost:9090
          predicates:
            - Path=/api/v2/activities/**

        - id: invoices
          uri: http://localhost:9080
          predicates:
            - Path=/api/v2/invoices/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /api/v2/activities
        name: Activity Service
      - url: /api/v2/clients
        name: Client Service
      - url: /api/v2/invoices
        name: Invoice Service